{% set version = "1.0" %}
{% set name = "AgrVATE" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: generic
  number: 0

source:
  url: https://github.com/VishnuRaghuram94/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 08126f72bfb4bb3a177168f7df06104d2c39177ae72cf65dd10e86ab7e94b50a

requirements:
  run:
    - blast
    - hmmer
    - seqkit
    - snippy  
    - mummer

test:
  commands:
    - "agrvate -h"
    - "agrvate -v"

about:
  home: https://github.com/VishnuRaghuram94/AgrVATE
  license: MIT
  license_file: LICENSE
  summary: Rapid identification of Staphylococcus aureus agr locus type and agr operon variants.
  
