{% set version = "1.0" %}
{% set name = "agrvate" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/VishnuRaghuram94/{{ name }}/archive/v{{ version }}.tar.gz

requirements:
  run:
    - blast
    - hmmer
    - seqkit	
    - snippy  
    - mummer

test:
  commands:
    - "agrvate -h"
    - "agrvate -v"

about:
  home: https://github.com/VishnuRaghuram94/{{ name }}
  license: ??
